# Generated by Django 4.2.7 on 2023-11-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_address', models.TextField(max_length=150)),
                ('city', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagram', models.CharField(max_length=200)),
                ('telegram', models.CharField(max_length=200)),
                ('whatsapp', models.CharField(max_length=200)),
            ],
        ),
    ]
