# Generated by Django 4.2.7 on 2023-12-07 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0002_massage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
